# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/resource_vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base/resource_vector.proto',
  package='firmament',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x62\x61se/resource_vector.proto\x12\tfirmament\"\x8d\x01\n\x0eResourceVector\x12\x11\n\tcpu_cores\x18\x01 \x01(\x02\x12\x0e\n\x06ram_bw\x18\x02 \x01(\x04\x12\x0f\n\x07ram_cap\x18\x03 \x01(\x04\x12\x0f\n\x07\x64isk_bw\x18\x04 \x01(\x04\x12\x10\n\x08\x64isk_cap\x18\x05 \x01(\x04\x12\x11\n\tnet_tx_bw\x18\x06 \x01(\x04\x12\x11\n\tnet_rx_bw\x18\x07 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESOURCEVECTOR = _descriptor.Descriptor(
  name='ResourceVector',
  full_name='firmament.ResourceVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_cores', full_name='firmament.ResourceVector.cpu_cores', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ram_bw', full_name='firmament.ResourceVector.ram_bw', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ram_cap', full_name='firmament.ResourceVector.ram_cap', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_bw', full_name='firmament.ResourceVector.disk_bw', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disk_cap', full_name='firmament.ResourceVector.disk_cap', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_tx_bw', full_name='firmament.ResourceVector.net_tx_bw', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_rx_bw', full_name='firmament.ResourceVector.net_rx_bw', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['ResourceVector'] = _RESOURCEVECTOR

ResourceVector = _reflection.GeneratedProtocolMessageType('ResourceVector', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEVECTOR,
  __module__ = 'base.resource_vector_pb2'
  # @@protoc_insertion_point(class_scope:firmament.ResourceVector)
  ))
_sym_db.RegisterMessage(ResourceVector)


# @@protoc_insertion_point(module_scope)
