# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/task_final_report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base/task_final_report.proto',
  package='firmament',
  syntax='proto3',
  serialized_pb=_b('\n\x1c\x62\x61se/task_final_report.proto\x12\tfirmament\"\xa8\x01\n\x0fTaskFinalReport\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12\x12\n\nstart_time\x18\x02 \x01(\x04\x12\x13\n\x0b\x66inish_time\x18\x03 \x01(\x04\x12\x14\n\x0cinstructions\x18\x04 \x01(\x04\x12\x0e\n\x06\x63ycles\x18\x05 \x01(\x04\x12\x10\n\x08llc_refs\x18\x06 \x01(\x04\x12\x12\n\nllc_misses\x18\x07 \x01(\x04\x12\x0f\n\x07runtime\x18\x08 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TASKFINALREPORT = _descriptor.Descriptor(
  name='TaskFinalReport',
  full_name='firmament.TaskFinalReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='firmament.TaskFinalReport.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='firmament.TaskFinalReport.start_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finish_time', full_name='firmament.TaskFinalReport.finish_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='firmament.TaskFinalReport.instructions', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycles', full_name='firmament.TaskFinalReport.cycles', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='llc_refs', full_name='firmament.TaskFinalReport.llc_refs', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='llc_misses', full_name='firmament.TaskFinalReport.llc_misses', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='firmament.TaskFinalReport.runtime', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['TaskFinalReport'] = _TASKFINALREPORT

TaskFinalReport = _reflection.GeneratedProtocolMessageType('TaskFinalReport', (_message.Message,), dict(
  DESCRIPTOR = _TASKFINALREPORT,
  __module__ = 'base.task_final_report_pb2'
  # @@protoc_insertion_point(class_scope:firmament.TaskFinalReport)
  ))
_sym_db.RegisterMessage(TaskFinalReport)


# @@protoc_insertion_point(module_scope)
